{
 "title": "Prometheus 2.0 统计",
 "tags": [ "prometheus" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Prometheus 作业",
    "query": {
     "query": "label_values(prometheus_build_info, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "样本写入速率",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(irate(prometheus_tsdb_head_samples_appended_total{job=\"${job}\"}[$__rate_interval]))",
     "legendFormat": "样本"
    }
   ]
  },
  {
   "title": "抓取耗时统计",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(5, max(scrape_duration_seconds) by (job))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "内存占用画像",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=\"${job}\"})",
     "legendFormat": "进程常驻内存"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"${job}\"}",
     "legendFormat": "虚拟内存"
    }
   ]
  },
  {
   "title": "WAL 日志损坏数",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "prometheus_tsdb_wal_corruptions_total{job=\"${job}\"}"
    }
   ]
  },
  {
   "title": "活跃写入器/句柄",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_active_appenders{job=\"${job}\"})",
     "legendFormat": "活跃写入器"
    },
    {
     "expr": "sum(process_open_fds{job=\"${job}\"})",
     "legendFormat": "打开文件句柄"
    }
   ]
  },
  {
   "title": "已加载数据块",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_blocks_loaded{job=\"${job}\"}",
     "legendFormat": "数据块"
    }
   ]
  },
  {
   "title": "内存内存块",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_chunks{job=\"${job}\"}",
     "legendFormat": "内存块"
    }
   ]
  },
  {
   "title": "Head 数据块 GC 活动",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_gc_duration_seconds{job=\"${job}\",quantile=\"0.99\"}",
     "legendFormat": "duration-p99"
    },
    {
     "expr": "irate(prometheus_tsdb_head_gc_duration_seconds_count{job=\"${job}\"}[$__rate_interval])",
     "legendFormat": "GC 次数"
    }
   ]
  },
  {
   "title": "数据压缩活动",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(prometheus_tsdb_compaction_duration_bucket{job=\"${job}\"}[$__rate_interval])) by (le))",
     "legendFormat": "duration-p99"
    },
    {
     "expr": "irate(prometheus_tsdb_compactions_total{job=\"${job}\"}[$__rate_interval])",
     "legendFormat": "压缩次数"
    },
    {
     "expr": "irate(prometheus_tsdb_compactions_failed_total{job=\"${job}\"}[$__rate_interval])",
     "legendFormat": "失败"
    },
    {
     "expr": "irate(prometheus_tsdb_compactions_triggered_total{job=\"${job}\"}[$__rate_interval])",
     "legendFormat": "触发"
    }
   ]
  },
  {
   "title": "配置重载统计",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_reloads_total{job=\"${job}\"}[$__rate_interval])",
     "legendFormat": "重载次数"
    },
    {
     "expr": "rate(prometheus_tsdb_reloads_failures_total{job=\"${job}\"}[$__rate_interval])",
     "legendFormat": "失败次数"
    }
   ]
  },
  {
   "title": "查询各阶段耗时",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "prometheus_engine_query_duration_seconds{job=\"${job}\", quantile=\"0.99\"}",
     "legendFormat": "{{slice}}_p99"
    }
   ]
  },
  {
   "title": "规则组评估耗时",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(prometheus_rule_group_duration_seconds{job=\"${job}\"}) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "规则组评估活动",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "rate(prometheus_rule_group_iterations_missed_total{job=\"${job}\"}[$__rate_interval])",
     "legendFormat": "错过"
    },
    {
     "expr": "rate(prometheus_rule_group_iterations_total{job=\"${job}\"}[$__rate_interval])",
     "legendFormat": "评估次数"
    }
   ]
  },
  {
   "title": "查询量（QPS）",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "qps" } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_engine_queries_total{job=\"${job}\"}[$__rate_interval]))",
     "legendFormat": "查询 QPS"
    }
   ]
  },
  {
   "title": "访问量（HTTP 请求量）",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_http_requests_total{job=\"${job}\"}[$__rate_interval]))",
     "legendFormat": "HTTP 请求量"
    }
   ]
  },
  {
   "title": "更新量（写入样本速率）",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(irate(prometheus_tsdb_head_samples_appended_total{job=\"${job}\"}[$__rate_interval]))",
     "legendFormat": "样本写入速率"
    }
   ]
  }
 ]
}