server:
  port: 9081

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/openhsd?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://8.134.221.22:3306/openhsd?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
#    password: Cend123...
    password: huashidai123
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secret: openhsd-gateway-jwt-secret-key-2026-make-it-long-enough-256bit
  issuer: openhsd

minio:
  endpoint: http://huashidai1.com:9000
  access-key: aibox
  secret-key: aiboxminio
  bucket-name: aiworkbox-images
  external-url: https://www.huashidai1.com/oss

